### PR TITLE
Search Page bugs fix

### LINKED ISSUE #299: BUG - Search page bugs (November)
Hey all,

Following the demo, I saw some bugs, so I'll just report them:

- Active icon should change SVG colour to `var(--vscode-button-foreground)`, for example, like GD does it already
Screenshot 2022-11-03 at 16 07 34

Screenshot 2022-11-03 at 16 08 07

- Clear filters button is wonky, rather imprecise. It also touches the text on the left when hover effect is turned on.

Screenshot 2022-11-03 at 16 09 21

Please properly align icon with the text, and tighten up the whole thing.

Screenshot 2022-11-03 at 16 13 13

- On scroll we lose the header with search bar. Let's not do that. Let's keep the search and header locked at the top, otherwise users have to scroll back to get to the search.

- Blue focus border is clipped. On the first element top/left/right is clipped, and on other ones left/right is clipped.

Screenshot 2022-11-03 at 16 15 11

Screenshot 2022-11-03 at 16 15 46

Use negative outline offset to push it inside, so it doesn't get clipped on the outside

Screenshot 2022-11-03 at 16 17 04

- We are using wrong loader. We should also give it some bottom margin so it's not touching the end of the screen.

Screenshot 2022-11-03 at 16 17 53

We have it already built in UI Components.

Screenshot 2022-11-03 at 16 19 18

- - - - 

@ckoutsiaris  @carwelsh

### PR DESCRIPTION
**Pull request by sanat-thukral**
# Search Page bugs fix

#299 

## Description

Minor UI bugs have been fixed

## Checklist for Pull Requests

- [x] Supplied as many details as possible on this change
- [x] Included the link to the associated issue in the Issue section above
- [x] The code conforms to the general [development guidelines](https://github.com/SAP/guided-answers-extension/blob/main/docs/developer-guide.md).
- [ ] The code has **unit tests** where applicable and is easily unit-testable
- [x] This branch is appropriately named for the associated issue

### CODE REVIEW

**Comment by Klaus-Keller** [comment]
Hi @sanat-thukral, 
I've checked the fixes and when light theme is active, the icons for product and component filters are now not visible unless I hover:



Could you please check?

**Review by Klaus-Keller — CHANGES_REQUESTED** [review]
see my comment about invisible icons.

**Comment by theStiggySpd** [comment]
please don't forget changeset too :-)

**Comment by sanat-thukral** [comment]
Thanks for the review @Klaus-Keller. The button has now been fixed :)
Screenshot 2022-12-08 at 12 07 52 a m

**Review by Klaus-Keller — CHANGES_REQUESTED** [review]
@sanat-thukral 
Icon issue is now fixed, however there are 3 code smells: https://sonarcloud.io/project/issues?id=SAP_guided-answers-extension&pullRequest=324&resolved=false&types=CODE_SMELL. Could you please check?

**Review by Klaus-Keller — APPROVED** [review]
- code is understandable and looks good
- installed, built, and tested locally and it works
- test coverage is excellent

Thanks @sanat-thukral for the fixes, approved from my side.

**Pull request merged**
