### PR TITLE
Feat/filtering-39-40-230

### PR DESCRIPTION
**Pull request by unseen1980**
# Issue

https://github.com/SAP/guided-answers-extension/issues/39
https://github.com/SAP/guided-answers-extension/issues/40
https://github.com/SAP/guided-answers-extension/issues/230

## Description

Add product and component filter functionality.

Screenshot 2022-09-20 at 11 38 57

## Checklist for Pull Requests

- [x] Supplied as many details as possible on this change
- [x] Included the link to the associated issue in the Issue section above
- [x] The code conforms to the general [development guidelines](https://github.com/SAP/guided-answers-extension/blob/main/docs/developer-guide.md).
- [x] The code has **unit tests** where applicable and is easily unit-testable
- [x] This branch is appropriately named for the associated issue

### CODE REVIEW

**Comment by Klaus-Keller** [comment]
@unseen1980, looks pretty neat, thanks!

Found 2 small things and pushed proposals:
- [x] Sequence _search -> filter -> search_ does not reset filter but searches with empty filter: [fix: update filter according to to search query](https://github.com/SAP/guided-answers-extension/pull/238/commits/206b4699bb81667a6aca98375ce35515edadff14)
- [x] inside filter dialog search field was not pinned to top: [fix: pin search field to top](https://github.com/SAP/guided-answers-extension/pull/238/commits/f62cc6144b23edd6f626c9c6b270859ab82644d3)

I've installed and build locally 🟢
Tested with local build 🟢
Code looks good to me 🟢
Code coverage is way better than nothing 🌕

While testing I've noticed a small inconsistency:
if you filter for Products it's alphabetically sorted
if you filter for Component it's sorted by occurrence in the search list

Should we align this behavior? @carwelsh @theStiggySpd, opinions?

**Comment by unseen1980** [comment]
@kl

> @unseen1980, looks pretty neat, thanks!
> 
> Found 2 small things and pushed proposals:
> 
> * [x]  Sequence _search -> filter -> search_ does not reset filter but searches with empty filter: [fix: update filter according to to search query](https://github.com/SAP/guided-answers-extension/pull/238/commits/206b4699bb81667a6aca98375ce35515edadff14)
> * [x]  inside filter dialog search field was not pinned to top: [fix: pin search field to top](https://github.com/SAP/guided-answers-extension/pull/238/commits/f62cc6144b23edd6f626c9c6b270859ab82644d3)
> 
> I've installed and build locally 🟢 Tested with local build 🟢 Code looks good to me 🟢 Code coverage is way better than nothing 🌕
> 
> While testing I've noticed a small inconsistency: if you filter for Products it's alphabetically sorted if you filter for Component it's sorted by occurrence in the search list
> 
> Should we align this behavior? @carwelsh @theStiggySpd, opinions?

Thanks @Klaus-Keller, I just added sorting for the components too.

**Comment by Klaus-Keller** [comment]
@unseen1980 found a small issue: If you have a filter set, open the filter dialog and click “Cancel”, the filter is cleared. I thing “Cancel” should do nothing and close the dialog.

**Comment by unseen1980** [comment]
> @unseen1980 found a small issue: If you have a filter set, open the filter dialog and click “Cancel”, the filter is cleared. I thing “Cancel” should do nothing and close the dialog.
> 
>  [  ](https://user-images.githubusercontent.com/66327622/191790106-60d802e3-a7fa-471a-bc98-8b6dfa3f83bf.gif) [ ](https://user-images.githubusercontent.com/66327622/191790106-60d802e3-a7fa-471a-bc98-8b6dfa3f83bf.gif)

We had this discussion with @ritarora and @carwelsh earlier. I did on purpose like this in case user wants to remove all the selected filters at once. We said to ask Goran. I can change it easily.

**Comment by Klaus-Keller** [comment]
>We had this discussion with @ritarora and @carwelsh earlier. I did on purpose like this in case user wants to remove all the selected filters at once. We said to ask Goran. I can change it easily.

Feels wrong to me. If filter is reset we should name the button "Reset Filter". "Cancel" suggests do nothing and close dialog.

Opinions @carwelsh @ritarora @theStiggySpd?

**Comment by unseen1980** [comment]
> > We had this discussion with @ritarora and @carwelsh earlier. I did on purpose like this in case user wants to remove all the selected filters at once. We said to ask Goran. I can change it easily.
> 
> Feels wrong to me. If filter is reset we should name the button "Reset Filter". "Cancel" suggests do nothing and close dialog.
> 
> Opinions @carwelsh @ritarora @theStiggySpd?

Yes, @ritarora proposed the same. I am ok with either

**Comment by Klaus-Keller** [comment]
Had a quick chat with @gpeuc, 
>Cancel should just close the window and do nothing.

**Comment by gpeuc** [comment]
Cancel should just drop the changes made in this particular "session", and act as some sort of Undo.

So, if I already have 3 filters checked, and I open the filter popup, and I click 2 more filters, but then I click Cancel, those 2 should be dropped, but we preserve the 3 that I already had.

I am also sort of hoping that we all here are using computers like 20 hours each day and that it's rather clear how Cancel works in pretty much all of the software 😄

**Comment by unseen1980** [comment]
> Cancel should just drop the changes made in this particular "session", and act as some sort of Undo.
> 
> So, if I already have 3 filters checked, and I open the filter popup, and I click 2 more filters, but then I click Cancel, those 2 should be dropped, but we preserve the 3 that I already had.
> 
> I am also sort of hoping that we all here are using computers like 20 hours each day and that it's rather clear how Cancel works in pretty much all of the software 😄


@gpeuc  I pushed a change that does this -> ```Cancel should just close the window and do nothing.```

The scenario you mentioned needs a bit of thinking on how to implement it so I propose to do it in a separate story. @carwelsh

**Comment by gpeuc** [comment]
@unseen1980 But isn't this: `Cancel should just close the window and do nothing.` the same as what I mentioned? Just closing the window and not saving anything that was done is that, no?

**Comment by unseen1980** [comment]
> @unseen1980 But isn't this: `Cancel should just close the window and do nothing.` the same as what I mentioned? Just closing the window and not saving anything that was done is that, no?

It is a bit technical, we have a global state for the requests to API and local state for selecting/deselecting the filters and on cancel we should re-update the global state with the previously selected filters of local state. Sorry can't explain it better. But anyway it doesn't matter now, I pushed the changes you want 🙂

**Comment by Klaus-Keller** [comment]
small commit to fix linting: https://github.com/SAP/guided-answers-extension/pull/238/commits/9f1c4d1b49a3e00a85adefda6c16e1975a03af16

**Review by Klaus-Keller — APPROVED** [review]
- build and tested locally again
- checked the code changes since last time

Approved, thanks @unseen1980!

**Comment by unseen1980** [comment]
Thank you all for your help 👍

**Pull request merged**
