### PR TITLE
release-strategy.md

### PR DESCRIPTION
**Pull request by carwelsh**
# Issue

#106

## Description

_FILL IN DETAILS HERE_

## Checklist for Pull Requests

- [ ] Supplied as many details as possible on this change
- [ ] Included the link to the associated issue in the Issue section above
- [ ] The code conforms to the general [development guidelines](https://github.com/SAP/guided-answers-extension/blob/main/docs/developer-guide.md).
- [ ] The code has **unit tests** where applicable and is easily unit-testable
- [ ] This branch is appropriately named for the associated issue

### CODE REVIEW

**Review by theStiggySpd — CHANGES_REQUESTED** [review]
Hello @carwelsh I suggest we hold off this pr for release strategy as we are still in talks with SAP Business Application Studio colleagues. So this timeline will not be accurate at this point.

**Comment by Klaus-Keller** [comment]
Hi @carwelsh, could you please link this new page in https://github.com/SAP/guided-answers-extension/blob/main/docs/README.md?

**Review by theStiggySpd — APPROVED** [review]
- Docs/Readme.md is update
- release-strategy and testing-strategy documents are good as it represents what we do today. We can add some more details in testing-strategy as we go along but for 1st version, looks good to me
Thanks for the changes

**Review by Klaus-Keller — APPROVED** [review]
- documentation on release/testing strategy look good
- tested links, all work

Approved from my side.

**Comment by theStiggySpd** [comment]
merging on @carwelsh's behalf.

Thanks colleagues.

**Pull request merged**
