### PR TITLE
fix(ga): not solved bug fixed

### PR DESCRIPTION
**Pull request by sanat-thukral**
# BUG: Not solved options missing in solved/not solved feature

#272 

## Description

Bug has been fixed, it was a minor iteration issue
Screenshot 2022-10-20 at 9 22 38 a m

_FILL IN DETAILS HERE_

## Checklist for Pull Requests

- [x] Supplied as many details as possible on this change
- [x] Included the link to the associated issue in the Issue section above
- [x] The code conforms to the general [development guidelines](https://github.com/SAP/guided-answers-extension/blob/main/docs/developer-guide.md).
- [ ] The code has **unit tests** where applicable and is easily unit-testable
- [x] This branch is appropriately named for the associated issue

### CODE REVIEW

**Comment by Klaus-Keller** [comment]
@sanat-thukral, please add a changeset using `pnpm changeset`

**Comment by sanat-thukral** [comment]
Thanks Klaus, sorry I missed your message earlier

**Comment by Klaus-Keller** [comment]
@sanat-thukral, now we have 2 change sets ;)

**Review by unseen1980 — APPROVED** [review]
👍

**Comment by sanat-thukral** [comment]
Thanks Christos :)

**Pull request merged**
