### PR TITLE
Feat/guided answers/header visibility 90

### PR DESCRIPTION
**Pull request by unseen1980**
This PR addresses the first task from this story https://github.com/SAP/guided-answers-extension/issues/90

1. Changes in folder structure for easier navigation
2. Move the header section into a new component and add props for the logo and nav button
3. Toggle off part of the header in the Details section

Screenshot 2022-06-01 at 09 17 54

### CODE REVIEW

**Review by Klaus-Keller — COMMENTED** [review]
@unseen1980, is it intended that the header is not visible when displaying the content of a Guided Answers node:

**Comment by unseen1980** [comment]
> @unseen1980, is it intended that the header is not visible when displaying the content of a Guided Answers node: 

Hi @Klaus-Keller, yes based on the designs. See point 3 in description. That's why I had to add those props in Header component.

**Comment by Klaus-Keller** [comment]
> Hi @Klaus-Keller, yes based on the designs. See point 3 in description. That's why I had to add those props in Header component.

@unseen1980 I see it now. The design have a search result page with header and a content page without header. Instead everything moves up and the back button becomes part of the content details. Are you planning to have this intermediate step as new version published or do you plan to continue implementing the rest of the new UX design?

**Comment by unseen1980** [comment]
> > Hi @Klaus-Keller, yes based on the designs. See point 3 in description. That's why I had to add those props in Header component.
> 
> @unseen1980 I see it now. The design has a search result page with header and a content page without header. Instead everything moves up and the back button becomes part of the content details. Are you planning to have this intermediate step as new version published or do you plan to continue implementing the rest of the new UX design?

Thanks @Klaus-Keller, I discussed this with @theStiggySpd and @carwelsh and we agreed that the PRs should have all the tasks of the story completed. So I am going to close this one and I'll create a new one when I have the rest of the tasks ready. Thanks

**Pull request closed without merging**
